---
title: Dockerfile Builder
description: Overview of dockerfile builder
---

import {Aside} from '@astrojs/starlight/components';

> Introduced in [**v1.8.0**](/changelog/v18)

<Aside type="caution" title='Docker build resource usage'>
The Docker build process can consume up to 100% of your server's resources, potentially slowing it to a crawl.
Make sure your server is powerful enough to handle it.
</Aside>

You can deploy services from a git repository if you have a `Dockerfile` inside of it.

![Dockerfile settings](/images/dockerfile-builder-settings.png)

- You can specify a **build context directory** for where the dockerfile should build your application, relative to the root of your repository
- You can specify the path of your **Dockerfile**, relative to the root of your repository
- And you can specify a **Docker build stage target** if you build your image using a multi-stage build and want to stop at a certain step of the build

