name: PR preview environment
on:
  # pull_request:
  workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        name: Deploy
        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - uses: oven-sh/setup-bun@v2
            with:
              bun-version: latest

          - name: Install packages and Deploy to zaneops
            shell: bash
            run: |
              cd scripts
              bun install
              bun run deploy-pr.ts
            env:
              CF_CLIENT_ID: ${{ secrets.CF_CLIENT_ID }}
              CF_CLIENT_SECRET: ${{ secrets.CF_CLIENT_SECRET }}
              PR_NUMBER: ${{ github.event.pull_request.number }}
              PR_BRANCH_NAME: ${{ github.head_ref }}
              ZANE_USERNAME: ${{ secrets.ZANE_USERNAME }}
              ZANE_PASSWORD: ${{ secrets.ZANE_PASSWORD }}

          - name: Read service URL
            id: read_url
            run: |
              url=$(cat ./scripts/service-url)
              echo "url=$url" >> $GITHUB_OUTPUT
          
          - name: Comment on PR
            uses: unsplash/comment-on-pr@v1.3.0
            env:
              GITHUB_TOKEN: ${{ secrets.COMMENT_PAT }}
            with:
              msg: 🚀 **PR Preview URL:** https://${{ steps.read_url.outputs.url }}
              check_for_duplicate_msg: true