name: Build and Push Images (DEV)
on:
  pull_request:
  workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        name: Deploy
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Bypass Cloudflare for GitHub Action
            uses: xiaotianxt/bypass-cloudflare-for-github-action@v1.1.1
            with:
              cf_zone_id: ${{ secrets.CF_ZONE_ID }}
              cf_api_token: ${{ secrets.CF_API_TOKEN }}
          - name: Deploy to ZaneOps
            run: |
              curl -f --silent -H "CF-Access-Client-Id: ${{ secrets.CF_CLIENT_ID }}" -H "CF-Access-Client-Secret: ${{ secrets.CF_CLIENT_SECRET }}" -X PUT ${{ secrets.GIT_DEPLOY_WEBHOOK_URL }}/fails