name: PR preview environment
on:
  pull_request:
  workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        name: Deploy
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          
          - uses: oven-sh/setup-bun@v2
            with:
              bun-version: latest

          - name: Install packages and Deploy to zaneops
            shell: bash
            run: |
              bun add cookie-es zod@3
              bun run scripts/deploy-pr.ts
            env:
              CF_CLIENT_ID: ${{ secrets.CF_ZONE_ID }}
              CF_CLIENT_SECRET: ${{ secrets.CF_API_TOKEN }}
              PR_NUMBER: ${{ github.event.pull_request.number }}
              PR_BRANCH_NAME: ${{ github.head_ref }}
              ZANE_USERNAME: ${{ secrets.ZANE_USERNAME }}
              ZANE_PASSWORD: ${{ secrets.ZANE_PASSWORD }}

